{{- if .Values.global.actorizer_cdc.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "actorizer_cdc.serviceAccountName" . }}
  labels:
    {{- include "actorizer_cdc.labels" . | nindent 4 }}
  {{- with .Values.global.actorizer_cdc.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.global.actorizer_cdc.serviceAccount.automount }}
{{- end }}
